[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc = "0.8.17"
remappings = ['@openzeppelin-contracts/=lib/openzeppelin-contracts/contracts/', 'solmate/=lib/solmate/src/']

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
